
const synonyms = {
    // --- Nouns (approx. 50) ---
    blog: ["article", "post", "entry", "column", "commentary"],
    writer: ["author", "blogger", "contributor", "scribe"],
    idea: ["concept", "notion", "thought", "approach", "hypothesis"],
    content: ["material", "text", "copy", "writing", "publication"],
    strategy: ["plan", "tactic", "approach", "method", "blueprint"],
    community: ["group", "network", "audience", "collective", "tribe"],
    audience: ["readers", "followers", "viewers", "subscribers", "public"],
    goal: ["objective", "aim", "target", "purpose", "mission"],
    knowledge: ["expertise", "understanding", "insight", "wisdom", "erudition"],
    data: ["information", "facts", "figures", "stats", "analytics"],
    tool: ["utility", "instrument", "device", "apparatus", "implement"],
    story: ["narrative", "tale", "account", "anecdote"],
    example: ["instance", "illustration", "case", "sample"],
    reason: ["cause", "motive", "explanation", "rationale"],
    business: ["company", "enterprise", "organization", "firm"],
    market: ["industry", "sector", "niche", "trade"],
    products: ["goods", "items", "merchandise", "wares"],
    services: ["offerings", "provisions", "solutions", "assistance"],
    customers: ["clients", "patrons", "consumers", "buyers"],
    website: ["site", "webpage", "platform", "portal"],
    result: ["outcome", "consequence", "effect", "conclusion"],
    feature: ["attribute", "trait", "characteristic", "element"],
    process: ["procedure", "method", "workflow", "system"],
    money: ["funds", "capital", "revenue", "income", "earnings"],
    success: ["achievement", "victory", "triumph", "accomplishment"],
    problem: ["challenge", "issue", "obstacle", "difficulty", "trouble"],
    solution: ["answer", "resolution", "fix", "remedy"],
    benefits: ["advantages", "perks", "gains", "merits"],
    challenges: ["obstacles", "hurdles", "roadblocks", "setbacks"],
    growth: ["expansion", "development", "progression", "increase"],
    opinion: ["view", "perspective", "belief", "stance"],
    opinion: ["view", "perspective", "belief", "stance"],
    project: ["task", "undertaking", "venture"],
    effort: ["endeavor", "attempt", "striving"],
    feedback: ["input", "comments", "critique"],
    demand: ["request", "requirement", "need"],
    demand: ["request", "requirement", "need"],
    impact: ["effect", "influence", "consequence"],
    development: ["growth", "progression", "evolution"],
    research: ["study", "investigation", "analysis"],
    experience: ["background", "expertise", "history"],
    approach: ["method", "tactic", "strategy"],
    change: ["alteration", "modification", "shift"],
    choice: ["option", "selection", "alternative"],
    control: ["power", "authority", "management"],
    deal: ["agreement", "transaction", "bargain"],
    decision: ["choice", "conclusion", "judgment"],
    decrease: ["reduction", "decline", "drop"],
    definition: ["meaning", "explanation", "description"],
    discussion: ["conversation", "dialogue", "debate"],
    
    // --- Verbs (approx. 80) ---
    create: ["develop", "generate", "produce", "build", "formulate"],
    make: ["create", "construct", "form", "fabricate", "forge"],
    use: ["utilize", "employ", "leverage", "apply", "harness"],
    help: ["assist", "aid", "support", "facilitate", "enable"],
    show: ["demonstrate", "illustrate", "display", "reveal", "present"],
    get: ["obtain", "acquire", "receive", "procure", "attain"],
    start: ["begin", "commence", "initiate", "launch", "embark"],
    end: ["finish", "conclude", "terminate", "complete", "cease"],
    think: ["believe", "consider", "ponder", "contemplate", "reflect"],
    understand: ["grasp", "comprehend", "perceive", "fathom", "realize"],
    explain: ["clarify", "elucidate", "describe", "detail", "expound"],
    analyze: ["examine", "evaluate", "study", "assess", "review"],
    improve: ["enhance", "better", "optimize", "refine", "upgrade"],
    connect: ["link", "relate", "associate", "join", "unite"],
    discover: ["find", "uncover", "reveal", "detect", "unearth"],
    share: ["distribute", "disseminate", "circulate", "impart"],
    believe: ["trust", "accept", "hold as true", "credit"],
    say: ["state", "declare", "mention", "assert", "remark"],
    write: ["compose", "pen", "draft", "author"],
    read: ["peruse", "scan", "study", "skim"],
    buy: ["purchase", "acquire", "procure", "invest in"],
    sell: ["market", "vend", "offer", "retail"],
    run: ["operate", "manage", "direct", "administer"],
    lead: ["guide", "direct", "supervise", "steer"],
    design: ["plan", "layout", "conceive", "formulate"],
    code: ["program", "develop", "script"],
    talk: ["speak", "discuss", "converse", "chat"],
    move: ["shift", "relocate", "transfer", "displace"],
    work: ["labor", "toil", "function", "operate"],
    publish: ["release", "issue", "post", "circulate"],
    research: ["investigate", "study", "examine", "explore"],
    compare: ["contrast", "equate", "liken", "weigh"],
    summarize: ["recapitulate", "abridge", "condense", "outline"],
    grow: ["expand", "increase", "develop", "flourish", "thrive"],
    provide: ["offer", "supply", "furnish", "deliver"],
    engage: ["involve", "interact", "attract", "captivate"],
    focus: ["concentrate", "highlight", "emphasize", "prioritize"],
    ask: ["inquire", "question", "request"],
    allow: ["permit", "let", "authorize"],
    apply: ["use", "utilize", "implement"],
    become: ["grow", "evolve", "turn into"],
    bring: ["carry", "transport", "deliver"],
    change: ["alter", "modify", "transform"],
    check: ["verify", "confirm", "inspect"],
    choose: ["select", "pick", "elect"],
    communicate: ["convey", "express", "interact"],
    consider: ["contemplate", "evaluate", "ponder"],
    continue: ["proceed", "persist", "carry on"],
    control: ["manage", "direct", "govern"],
    deliver: ["provide", "supply", "give"],
    describe: ["portray", "depict", "illustrate"],
    determine: ["decide", "establish", "find out"],
    discuss: ["talk about", "converse", "address"],
    do: ["perform", "execute", "act"],
    drive: ["propel", "motivate", "push"],
    ensure: ["guarantee", "secure", "make sure"],
    evaluate: ["assess", "appraise", "judge"],
    examine: ["inspect", "analyze", "study"],
    exist: ["be", "live", "subsist"],
    expect: ["anticipate", "foresee", "predict"],
    experience: ["undergo", "encounter", "live through"],
    follow: ["obey", "comply with", "adhere to"],
    give: ["provide", "offer", "grant"],
    have: ["possess", "own", "hold"],
    identify: ["recognize", "pinpoint", "name"],
    implement: ["execute", "apply", "enact"],
    increase: ["raise", "grow", "expand"],
    indicate: ["show", "point out", "signal"],
    influence: ["affect", "impact", "sway"],
    inform: ["tell", "notify", "apprise"],
    involve: ["include", "entail", "comprise"],
    keep: ["retain", "hold", "preserve"],
    know: ["be aware of", "understand", "recognize"],
    learn: ["study", "master", "acquire knowledge"],
    
    // --- Adjectives (approx. 70) ---
    quick: ["fast", "rapid", "swift", "speedy"],
    happy: ["joyful", "content", "pleased", "cheerful"],
    small: ["tiny", "little", "miniature", "petite"],
    big: ["large", "huge", "massive", "substantial"],
    new: ["recent", "latest", "modern", "current"],
    good: ["great", "excellent", "effective", "valuable", "superb"],
    bad: ["poor", "terrible", "negative", "harmful", "detrimental"],
    important: ["crucial", "essential", "vital", "critical", "significant"],
    interesting: ["engaging", "fascinating", "compelling", "noteworthy", "captivating"],
    easy: ["simple", "straightforward", "effortless", "uncomplicated"],
    hard: ["difficult", "challenging", "complex", "tough", "arduous"],
    useful: ["helpful", "beneficial", "valuable", "advantageous", "practical"],
    unique: ["distinctive", "unusual", "novel", "exclusive", "one-of-a-kind"],
    awesome: ["amazing", "fantastic", "incredible", "terrific", "splendid"],
    key: ["main", "primary", "fundamental", "principal"],
    really: ["truly", "genuinely", "very", "certainly"],
    very: ["extremely", "highly", "exceptionally", "remarkably"],
    quickly: ["rapidly", "swiftly", "promptly", "hastily"],
    slowly: ["gradually", "leisurely", "steadily", "unhurriedly"],
    creative: ["inventive", "imaginative", "artistic", "innovative"],
    simple: ["basic", "uncomplicated", "plain", "clear"],
    complex: ["intricate", "complicated", "elaborate", "involved"],
    free: ["complimentary", "gratis", "unpaid", "cost-free"],
    paid: ["premium", "subscription", "monetized", "fee-based"],
    online: ["digital", "web-based", "internet", "virtual"],
    offline: ["physical", "real-world", "in-person"],
    personal: ["individual", "private", "custom", "tailored"],
    professional: ["expert", "formal", "skilled", "adept"],
    global: ["worldwide", "international", "universal", "planetary"],
    local: ["regional", "community", "native"],
    clear: ["obvious", "apparent", "evident", "lucid"],
    different: ["various", "diverse", "distinct", "unlike"],
    full: ["complete", "entire", "whole", "comprehensive"],
    empty: ["vacant", "void", "bare", "hollow"],
    fast: ["quick", "rapid", "swift", "brisk"],
    slow: ["leisurely", "gradual", "unhurried", "plodding"],
    main: ["chief", "primary", "principal", "major"],
    final: ["last", "ultimate", "concluding", "terminal"],
    early: ["premature", "ahead of time", "soon"],
    late: ["delayed", "tardy", "overdue"],
    first: ["initial", "primary", "premier"],
    last: ["final", "ultimate", "terminal"],
    certain: ["sure", "positive", "confident"],
    possible: ["likely", "probable", "plausible"],
    effective: ["efficient", "productive", "successful", "potent"],
    certain: ["sure", "positive", "confident", "convinced"],
    able: ["capable", "competent", "skilled"],
    actual: ["real", "genuine", "true"],
    additional: ["extra", "supplementary", "further"],
    adequate: ["sufficient", "enough", "ample"],
    advanced: ["developed", "complex", "sophisticated"],
    apparent: ["obvious", "evident", "clear"],
    appropriate: ["suitable", "proper", "fitting"],
    available: ["accessible", "obtainable", "ready"],
    basic: ["fundamental", "essential", "primary"],
    beautiful: ["gorgeous", "stunning", "attractive"],
    better: ["superior", "improved", "preferable"],
    brief: ["short", "concise", "summary"],
    common: ["usual", "ordinary", "widespread"],
    complete: ["full", "entire", "whole"],
    correct: ["right", "accurate", "proper"],
    current: ["present", "existing", "ongoing"],
    deep: ["profound", "intense", "submerged"],
    direct: ["straight", "uninterrupted", "immediate"],
    dominant: ["leading", "primary", "prevalent"],
};

function getRandomSynonym(word) {
    const lower = word.toLowerCase();
    if (synonyms[lower]) {
        const options = synonyms[lower];
        return options[Math.floor(Math.random() * options.length)];
    }
    return word;
}

export function rewriteText(text) {
    return text
        .split(/\b/)
        .map(word => {
            if (/^[a-zA-Z]+$/.test(word)) {
                if (Math.random() > 0.5) {
                    return getRandomSynonym(word) || word;
                }
            }
            return word;
        })
        .join('');
}
